codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "*.pyc"
  - "__pycache__"
  - "collector/tests/"
  - "*.md"

